branch-defaults:
  master:
    environment: speechtoText-dev
    group_suffix: null
environment-defaults:
  speechtoText-dev:
    branch: null
    repository: null
global:
  application_name: speechtoText
  branch: null
  default_ec2_keyname: text-speech
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
